// Reads shared/prompts.md (canonical, human-edited), extracts each agent's
// system prompt from its fenced code block, and writes them as string
// exports to supabase/functions/_shared/prompts.ts (bundled into every
// Edge Function that imports from ../_shared/prompts.ts).
//
// Run this whenever you edit shared/prompts.md, then commit both files.
//
//   node scripts/sync-prompts.mjs

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const SRC = resolve(REPO_ROOT, "shared/prompts.md");
const DEST = resolve(REPO_ROOT, "supabase/functions/_shared/prompts.ts");

// Matches:  "## A<n> - <anything>\n\n```<optional lang>\n<prompt>\n```"
const PATTERN = /##\s*A(\d+)\b[^\n]*\n+```(?:\w+)?\n([\s\S]*?)\n```/g;

const REQUIRED = ["1", "2", "3"];

const src = await readFile(SRC, "utf8");

const found = new Map();
for (const m of src.matchAll(PATTERN)) {
  found.set(m[1], m[2].trim());
}

const missing = REQUIRED.filter((n) => !found.has(n));
if (missing.length > 0) {
  console.error(
    `sync-prompts: missing prompt(s) A${missing.join(", A")} in ${relative(REPO_ROOT, SRC)}`,
  );
  process.exit(1);
}

const banner = `// AUTO-GENERATED by scripts/sync-prompts.mjs. Do not edit by hand.
// Source of truth: shared/prompts.md
// Regenerate: node scripts/sync-prompts.mjs
`;

const body = REQUIRED
  .map((n) => `\nexport const A${n}_SYSTEM_PROMPT = ${JSON.stringify(found.get(n))};\n`)
  .join("");

await mkdir(dirname(DEST), { recursive: true });
await writeFile(DEST, banner + body);

console.log(
  `sync-prompts: wrote ${REQUIRED.length} prompts to ${relative(REPO_ROOT, DEST)}`,
);
